# Generated by Django 3.2.5 on 2022-06-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_animal_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='name',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='date_fabrication',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='is_active',
        ),
        migrations.AddField(
            model_name='animal',
            name='peso',
            field=models.TextField(default=1, max_length=10, verbose_name='Peso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='raca',
            field=models.TextField(default=1, max_length=50, verbose_name='raca'),
            preserve_default=False,
        ),
    ]
