# Generated by Django 3.2.5 on 2022-06-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_auto_20220628_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.CharField(max_length=20, verbose_name='raca'),
        ),
    ]
