# Generated by Django 3.2.5 on 2022-06-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0004_alter_animal_raca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='peso',
            field=models.CharField(max_length=10, verbose_name='Peso'),
        ),
    ]
