# Generated by Django 3.2.5 on 2022-06-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='name',
            new_name='nome',
        ),
    ]
