# Generated by Django 3.2.5 on 2022-06-25 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('descricao', models.TextField(max_length=100, verbose_name='Descricao')),
                ('valor', models.FloatField(blank=True, default=0.0, null=True, verbose_name='valor')),
                ('tempo_execucao', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tempo execucao')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipos.tipo')),
            ],
            options={
                'verbose_name': 'Servico',
                'verbose_name_plural': 'Servicos',
                'ordering': ['id'],
            },
        ),
    ]
