# Generated by Django 3.2.5 on 2022-06-26 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='tempo_execucao',
            new_name='tempoexecucao',
        ),
    ]
