# Generated by Django 3.2.5 on 2022-06-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_rename_tempo_execucao_servico_tempoexecucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='tempoexecucao',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tempo execucao'),
        ),
    ]
