# Generated by Django 3.2.5 on 2022-06-27 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_rename_tempo_execucao_servico_tempoexecucao'),
        ('animais', '0002_animal_cliente'),
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='animais.animal'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AtendimentoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimentos.atendimento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servico')),
            ],
            options={
                'verbose_name': 'Itens de Servico',
                'verbose_name_plural': 'Itens de Servicos ',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='atendimento_servico',
            field=models.ManyToManyField(blank=True, through='atendimentos.AtendimentoServico', to='servicos.Servico'),
        ),
    ]
