# Generated by Django 3.2.5 on 2022-06-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_auto_20220626_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='photo',
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='date_fabrication',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='name',
            field=models.CharField(max_length=50, verbose_name='codigo'),
        ),
    ]
